# Autogenerated with SMOP 0.35
from smop.core import *
# bispectrum.m

    
    Y,FS=audioread('Wheeze.mp3',nargout=2)
# bispectrum.m:2
    plot(Y[:,1])
    F=ifft(Y)
# bispectrum.m:4
    G=fft(Y)
# bispectrum.m:5
    Bi=dot(dot(F[95],G[90]),G[5])
# bispectrum.m:6