# Autogenerated with SMOP 0.35
from smop.core import *
# crestFactor.m

    Y,FS=audioread('Crackles - Low Pitched (Rales).mp3',nargout=2)
# crestFactor.m:1
    x=Y[:,1]
# crestFactor.m:2
    maxval=max(x)
# crestFactor.m:3
    s=std(x)
# crestFactor.m:4
    crestFactor=dot(20,log10(maxval / s))
# crestFactor.m:5