# Autogenerated with SMOP 
from smop.core import *
# logvariance.m

    Y,FS=audioread('Crackles - Low Pitched (Rales).mp3',nargout=2)
# logvariance.m:1
    x=Y[:,1]
# logvariance.m:2
    mu=mean(x.T)
# logvariance.m:4
    s=std(x)
# logvariance.m:5
    
    M,V=lognstat(mu,s,nargout=2)
# logvariance.m:7