# Autogenerated with SMOP 0.35
from smop.core import *
# power_spectral_density.m

    Y,FS=audioread('Crackles - Low Pitched (Rales).mp3',nargout=2)
# power_spectral_density.m:1
    x=Y[:,1]
# power_spectral_density.m:2
    psd=pwelch(x)
# power_spectral_density.m:4