# Autogenerated with SMOP 0.35
from smop.core import *
# skewness_kurtosis.m

    Y,FS=audioread('Crackles - Low Pitched (Rales).mp3',nargout=2)
# skewness_kurtosis.m:1
    x=Y[:,1]
# skewness_kurtosis.m:2
    plot(x)
    skew=skewness(x)
# skewness_kurtosis.m:4
    kurt=kurtosis(x)
# skewness_kurtosis.m:5