# Autogenerated with SMOP 0.35
from smop.core import *
# zerocross.m

    x,Fs=audioread('Crackles - Early Inspiratory (Rales).mp3',nargout=2)
# zerocross.m:1
    left_channel=x[:,1]
# zerocross.m:2
    zero_cross=size(find(diff(left_channel > 0) != 0) + 1)
# zerocross.m:4