# Autogenerated with SMOP 0.35
from smop.core import *
# fundamental_frequency.m

    x,Fs=audioread('Crackles - Early Inspiratory (Rales).mp3',nargout=2)
# fundamental_frequency.m:1
    left_channel=x[:,1]
# fundamental_frequency.m:2
    fleft_channel=fft(left_channel)
# fundamental_frequency.m:4
    freq=arange(0,Fs / 2,Fs / length(fleft_channel))
# fundamental_frequency.m:5
    fleft_channel=fleft_channel[1:length(fleft_channel) / 2 + 1]
# fundamental_frequency.m:6
    plot(freq,abs(fleft_channel))
    maxval,index=max(abs(fleft_channel),nargout=2)
# fundamental_frequency.m:8
    freq[index]